### ISSUE TITLE
The LLM returns the code, but the editor does not show it.

### ISSUE THREAD

**Issue by mountisome** [arshad-yaseen/monacopilot#86] opened 2024-11-26 04:43 UTC
Hello, thanks for your code. But I have met a problem. I only use registerCompletion like this:
```javascript
registerCompletion(monaco, editor, {
      endpoint: xxx,
      language: 'javascript',
      trigger: 'onIdle',
      onError: error => {
        console.error(error);
      },
      requestHandler: async ({endpoint, body}) => {
        const response = await fetch(endpoint, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer xxx'
          },
          body: JSON.stringify({
            ...body,
            xxx
          }),
        });

        const data = await response.json();
        console.log(data.message.content);
        return {
          completions: data.message.content,
        }
      }
    })
```
The console could print the code, but the editor does not show. I dont know the reason. The LLM responses the code slowly and I am not sure maybe it causes it.

**Comment by arshad-yaseen** [comment] 2024-12-01 13:42
Hey @mountisome, I’ve tried many cases, and this issue hasn’t occurred for me since I made the last changes to the range calculations. Please update Monacopilot to the latest version and let me know if this happens again. If it does, share the code in the editor and the cursor's position at that time.

**Comment by mountisome** [comment] 2024-12-02 03:55
Hello, I updated Monacopilot to the latest version but the editor did not show the code. I use Vue2 and Monacopilot v0.15.4. I refer the example of Vue to use monacopilot and my code is like this:
```javascript
mounted() {
    const editor = monaco.editor.create(this.$refs.editor, {
	language: this.language,
    });

    registerCompletion(monaco, editor, {
      endpoint: xxx,
      language: this.language,
      trigger: 'onTyping',
      onError: error => {
        console.error(error);
      },
      requestHandler: async ({endpoint, body}) => {
        const response = await fetch(endpoint, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': xxx
          },
          body: JSON.stringify({
            ...body,
            'model': xxx,
            'messages': [
                xxx
            ]
          }),
        });

        const data = await response.json();
        console.log(data.message.content);
        return {
          completions: data.message.content,
        }
      }
    });
}
```
I did not use the cursor's position and I think maybe it is the reason. But I dont know how to use the cursor's position.

**Comment by liwenye123** [comment] 2024-12-05 02:43
I have the same problem, when the cursor is on the last line, the request triggers, and ghost text displays normally. When the cursor is in the middle of the text, click Line Break or enter a code. The request is triggered. The large model returns code, but ghost text is not displayed. What is the cause? Can you share the solution?

**Comment by liwenye123** [comment] 2024-12-05 02:44
> Hey @mountisome, I’ve tried many cases, and this issue hasn’t occurred for me since I made the last changes to the range calculations. Please update Monacopilot to the latest version and let me know if this happens again. If it does, share the code in the editor and the cursor's position at that time.

I have the same problem, when the cursor is on the last line, the request triggers, and ghost text displays normally. When the cursor is in the middle of the text, click Line Break or enter a code. The request is triggered. The large model returns code, but ghost text is not displayed. What is the cause? Can you share the solution? thanks

**Comment by liwenye123** [comment] 2024-12-05 02:52
> > Hey @mountisome, I’ve tried many cases, and this issue hasn’t occurred for me since I made the last changes to the range calculations. Please update Monacopilot to the latest version and let me know if this happens again. If it does, share the code in the editor and the cursor's position at that time.
> 
> I have the same problem, when the cursor is on the last line, the request triggers, and ghost text displays normally. When the cursor is in the middle of the text, click Line Break or enter a code. The request is triggered. The large model returns code, but ghost text is not displayed. What is the cause? Can you share the solution? and my code is like this, thanks

```javascript
completion_ = registerCompletion(monaco, editor, {
        language: 'python',
        trigger: 'onTyping',
        maxContextLines: 100,
        endpoint: 'xxx',
        requestHandler: async ({ endpoint, body }) => {
          try {
            const data = await callCodeCompletion({endpoint, body});
            console.log('Completion Code: ', data);
            return { completion: data };
          } catch (error) {
            console.error('Fetch error:', error);
            return { completion: null};
          }
        },
      });

**Comment by arshad-yaseen** [comment] 2024-12-05 09:14
@liwenye123 @mountisome Sure, No worries! Will push the fix very soon.

**Comment by arshad-yaseen** [comment] 2024-12-06 00:14
@liwenye123 @mountisome Released `v0.15.5` 🚀 Please update Monacopilot to the latest version. The new fix ensures that ghost text always appears in the editor. If you notice anything related to this or other issues, please feel free to let me know.

**Comment by arshad-yaseen** [comment] 2024-12-06 00:14
https://github.com/arshad-yaseen/monacopilot/releases/tag/v0.15.5

**Comment by liwenye123** [comment] 2024-12-06 01:44
> @liwenye123 @mountisome Released `v0.15.5` 🚀 Please update Monacopilot to the latest version. The new fix ensures that ghost text always appears in the editor. If you notice anything related to this or other issues, please feel free to let me know.

thanks very much👍👍👍👍👍it works

**Comment by mountisome** [comment] 2024-12-06 08:35
> @liwenye123 @mountisome Released `v0.15.5` 🚀 Please update Monacopilot to the latest version. The new fix ensures that ghost text always appears in the editor. If you notice anything related to this or other issues, please feel free to let me know.

However, the ghost text didn't show in my editor and what should I do to my code:
```javascript
mounted() {
    const editor = monaco.editor.create(this.$refs.editor, {
	language: this.language,
    });

    registerCompletion(monaco, editor, {
      endpoint: xxx,
      language: this.language,
      trigger: 'onTyping',
      onError: error => {
        console.error(error);
      },
      requestHandler: async ({endpoint, body}) => {
        const response = await fetch(endpoint, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': xxx
          },
          body: JSON.stringify({
            ...body,
            'model': xxx,
            'messages': [
                xxx
            ]
          }),
        });

        const data = await response.json();
        console.log(data.message.content);
        return {
          completions: data.message.content,
        }
      }
    });
}
```

**Comment by arshad-yaseen** [comment] 2024-12-06 08:52
@mountisome First of all, make sure you have updated Monacopilot to the latest version. 
In your code, you are providing `model` and `messages` in the body of the fetch request. 
The thing is, you don't need to do this. The `body` from `requestHandler`, which you spread into the fetch body, 
already includes `model`, `messages`, and other necessary data along with the prompt generated internally by Monacopilot. 
Providing `model` and `messages` manually in the body causes the issue.

There ar rules that apply to the prompt, and the editor expects a specific format from the LLM to process the completion correctly. If your prompt isn't formatted well enough, the completion won't appear in the editor because it wouldn't make sense to display it there. If you want to provide custom prompt, This is the official way to do it: https://github.com/arshad-yaseen/monacopilot?tab=readme-ov-file#custom-prompt

So your final code should look like:

```javascript
mounted() {
    const editor = monaco.editor.create(this.$refs.editor, {
	language: this.language,
    });

    registerCompletion(monaco, editor, {
      endpoint: xxx,
      language: this.language,
      trigger: 'onTyping',
      onError: error => {
        console.error(error);
      },
      requestHandler: async ({endpoint, body}) => {
        const response = await fetch(endpoint, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': xxx
          },
          body: JSON.stringify(body), // Edited here
        });

        const data = await response.json();
        console.log(data.message.content);
        return {
          completions: data.message.content,
        }
      }
    });
}
```

**Comment by arshad-yaseen** [comment] 2024-12-06 08:56
@mountisome @liwenye123 I see you both using `requestHandler`,  I don't see a use case for it in your code. If your intention is to use a custom LLM model for completion, you can achieve this by providing a custom model when creating a Copilot instance. Here's how to do it: https://github.com/arshad-yaseen/monacopilot?tab=readme-ov-file#custom-model.

Otherwise, you can simply remove `requestHandler`, and Monacopilot will handle the fetch part for you.
Or do you have any other specific use cases for it?

**Comment by mountisome** [comment] 2024-12-09 09:02
@arshad-yaseen Hello, I used `registerCompletion` with `model` and `messages` because the model I use require these parameters. I have tried change `registerCompletion` to `Copilot` and my code was like this:
```javascript
const copilot = new Copilot('xx', {
      model: {
        config: (apiKey, prompt) => ({
          endpoint: 'https://api-inference.huggingface.co/models/openai-community/gpt2',
          headers: {
            Authorization: `Bearer ${apiKey}`,
            'Content-Type': 'application/json',
          },
          body: {
            inputs: prompt.user,
            parameters: {
              max_length: 100,
              num_return_sequences: 1,
              temperature: 0.7,
            },
          },
        }),
        transformResponse: response => ({text: response[0].generated_text}),
      },
    });

    const customPrompt = () => ({
      system: 'You are an AI assistant specialized in JavaScript and you should help me complete my code.',
      user: 'function bubbleSort() {',
    });

    copilot.complete({
      options: {customPrompt},
    });
```
But I have met the problem: **Uncaught (in promise) TypeError: Cannot destructure property 'completionMetadata' of 'o' as it is undefined.** and I don't know the reason. Could you help me solve it. Thanks a lot.

**Comment by arshad-yaseen** [comment] 2024-12-09 16:09
@mountisome I tried copying your code and running the completion. It works without any errors. Could you please send the full Monacopilot code you used? This will help me understand the issue more clearly!

**Comment by mountisome** [comment] 2024-12-10 02:15
@arshad-yaseen My full code is this:
```javascript
mounted() {
    this.editor = monaco.editor.create(this.$refs.editor, {
      language: 'javascript',
    });

    const copilot = new Copilot('xxx', {
      model: {
        config: (apiKey, prompt) => ({
          endpoint: 'https://api-inference.huggingface.co/models/openai-community/gpt2',
          headers: {
            'Authorization': `Bearer ${apiKey}`,
            'Content-Type': 'application/json',
          },
          body: {
            inputs: prompt.user,
            parameters: {
              max_length: 100,
              num_return_sequences: 1,
              temperature: 0.7,
            },
          },
        }),
        transformResponse: response => ({text: response[0].generated_text}),
      },
    });

    const customPrompt = () => ({
      system: 'You are an AI assistant specialized in JavaScript and you should help me complete my code.',
      user: 'function bubbleSort() {',
    });

    copilot.complete({
      options: {customPrompt},
    });
  },
  ```
and the error: **Uncaught (in promise) TypeError: Cannot destructure property 'completionMetadata' of 'o' as it is undefined.**

**Comment by arshad-yaseen** [comment] 2024-12-10 08:30
@mountisome I mean with `registerCompletion`

**Comment by mountisome** [comment] 2024-12-13 02:59
@arshad-yaseen I use `registerCompletion` like this:
```javascript
mounted() {
    const editor = monaco.editor.create(this.$refs.editor, {
      language: 'javascript',
    });

     registerCompletion(monaco, editor, {
      endpoint: 'https://api-inference.huggingface.co/models/openai-community/gpt2',
      language: this.language,
      trigger: 'onTyping',
      onError: error => {
        console.error(error);
      },
      requestHandler: async ({endpoint, body}) => {
        const response = await fetch(endpoint, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer xxx'
          },
          body: JSON.stringify(body), 
        });

        const data = await response.json();
        console.log(data.message.content);
        return {
          completions: data.message.content,
        }
      }
    });
  },
```
If I want to change the body, how can I do it?

**Comment by arshad-yaseen** [comment] 2024-12-18 20:10
Hey @mountisome,

Here's what's going wrong and how to fix it:

### Problems in Your Current Code

**1. Returning `completions` Instead of `completion`:**
```javascript
// ❌ Incorrect:
return {
  completions: data.message.content,
}

// ✅ Correct:
return {
  completion: data.message.content,
}
```

**2. Using the Hugging Face endpoint directly in registerCompletion:**
```javascript
// ❌ Incorrect (client-side):
registerCompletion(monaco, editor, {
  endpoint: 'https://api-inference.huggingface.co/models/openai-community/gpt2', 
  // ...
});
```
Instead, you should have a server-side API handler that uses copilot.complete to call Hugging Face, and then registerCompletion should point to that server endpoint.

**3. Defining Copilot and calling copilot.complete client-side with API keys:**
```javascript
// ❌ Incorrect (client-side with API keys):
const copilot = new Copilot('YOUR_HF_API_KEY', { /* model config */ });
copilot.complete({ /* ... */ });
```
The API keys and the actual copilot.complete call must be on the server side.

### How to Fix It

#### Server-side (Node.js) Example:
```javascript
// ✅ Server code (e.g., api/complete.js)
import express from 'express';
import { Copilot } from 'monacopilot';

const app = express();
app.use(express.json());

const copilot = new Copilot(process.env.HF_API_KEY, {
  model: {
    config: (apiKey, prompt) => ({
      endpoint: 'https://api-inference.huggingface.co/models/openai-community/gpt2',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: {
        inputs: prompt.user,
        parameters: {
          max_length: 100,
          num_return_sequences: 1,
          temperature: 0.7,
        },
      },
    }),
    transformResponse: response => ({ text: response[0].generated_text }),
  },
});

app.post('/complete', async (req, res) => {
  const { completion, error } = await copilot.complete({ body: req.body });

  if (error) {
    return res.status(500).json({ completion: null, error });
  }

  return res.json({ completion });
});

app.listen(3000);
```

#### Client-side:
```javascript
// ✅ Client code
import * as monaco from 'monaco-editor';
import { registerCompletion } from 'monacopilot';

const editor = monaco.editor.create(document.getElementById('editor'), {
  language: 'javascript',
});

registerCompletion(monaco, editor, {
  endpoint: 'https://api.example.com/complete', // Now pointing to your server endpoint
  language: 'javascript',
  trigger: 'onTyping',
  onError: error => console.error(error),
});
```

This separation ensures:
- You return completion (not completions).
- The Hugging Face model call is handled server-side (no direct calls from the client).
- Your API keys stay safe on the server.

**Comment by mountisome** [comment] 2024-12-19 04:43
@arshad-yaseen Hello, thanks for your code. But I have met the new error: `[MONACOPILOT ERROR] fetch is not defined` when I use the above code. And my code:
```javascript
// complete.mjs

import express from 'express';
import { Copilot } from 'monacopilot';
import cors from 'cors';

const app = express();
app.use(express.json());

app.use(cors({
  origin: 'http://localhost:8080',
  methods: ['GET', 'POST', 'PUT', 'DELETE'],
  allowedHeaders: ['Content-Type', 'Authorization']
}));

const copilot = new Copilot('xx', {
  model: {
    config: (apiKey, prompt) => ({
      endpoint: 'https://api-inference.huggingface.co/models/openai-community/gpt2',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: {
        inputs: 'sort',
        parameters: {
          max_length: 100,
          num_return_sequences: 1,
          temperature: 0.7,
        },
      },
    }),
    transformResponse: response => ({ text: response[0].generated_text }),
  },
});

app.post('/complete', async (req, res) => {
  const { completion, error } = await copilot.complete({ body: req.body });

  if (error) {
    return res.status(500).json({ completion: null, error });
  }

  return res.json({ completion });
});

app.listen(3000);
```

**Comment by arshad-yaseen** [comment] 2024-12-19 08:35
@mountisome Oh, this issue might be occurring because your Node.js version is older than v18. This error can be fixed by upgrading to Node.js v18 or higher. The error occurs because copilot.complete uses native `fetch`, which isn't supported in Node.js versions below 18.

Here are the solutions:

1. Upgrade your Node.js to v18 or higher (recommended).
2. If you don't want to upgrade to v18 or higher, I can suggest an alternative. We can introduce a new option in the Copilot instance called `customFetch`, allowing you to use node-fetch instead. Here's an example:

   ```javascript
   import fetch from 'node-fetch'
   const copilot = new Copilot('...', {
       model: {},
   }, {
       customFetch: fetch,
   });
   ```

Let me know if you'd prefer the second option, and I can help you implement it (option 1 is recommended).

**Comment by mountisome** [comment] 2024-12-23 08:21
@arshad-yaseen Hello, the problem is solved. Thanks a lot~

**Closed as completed** 2024-12-23 09:15 UTC
